# Generated by Django 4.2.5 on 2023-09-12 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='название курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_image/', verbose_name='изображение для курса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='название лекции')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons_image/', verbose_name='изображение для лекции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='ссылка')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'лекция',
                'verbose_name_plural': 'лекции',
                'ordering': ('course',),
            },
        ),
    ]
