# Generated by Django 4.2.5 on 2023-09-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_tests_questions_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='ответ на вопрос'),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
