# Generated by Django 4.2.5 on 2023-09-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_questions_answer_delete_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='название курса'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='название лекции'),
        ),
    ]
